// Contenido estático de tarifas y transbordos AUVASA.
// Fuentes: web ArroyoBus, Junta CyL (BusCyL), AUVASA.

export const TARIFAS_TEXT = [
  "💳 <b>Tarifas y tarjeta BusCyL</b>",
  "",
  "🎫 <b>Billete ordinario (pago en efectivo)</b>: 1,80 €",
  "💳 <b>Con tarjeta BusCyL</b>",
  "💳 <b>Con tarjeta metropolitana (marrón/granate)</b>",
    "",
  "<b>¿Qué es la tarjeta BusCyL?</b>",
  "Es la tarjeta única de transporte de Castilla y León. Sustituye a los antiguos abonos metropolitanos y carnés de transporte gratuito (jubilado, familia numerosa, etc.). Con ella:",
  "• Pagas gratis tu viaje.",
  "• Aprovechas transbordos gratuitos.",
  "",
  "ℹ️ Solicítala gratis en <a href=\"https://buscyl.es\">la página web Buscyl</a> o en oficinas de la estación.",
].join("\n");

export const COMBINAR_TEXT = [
  "🔁 <b>Combinar con AUVASA (Valladolid)</b>",
  "",
  "Con la tarjeta <b>BusCyL</b> el transbordo entre ArroyoBus y AUVASA NO es <b>gratuito</b> deberás disponer de un bonobús de AUVASA o el QR desde la aplicación AUVASA PAY. <a href=\"https://www.auvasa.es/tarifas-y-medios-de-pago/\">Consulta más medios de pago aceptados por AUVASA aquí/</a>",
  "",
  "<b>Nodos de transbordo recomendados:</b>",
  "",
  "🏥 <b>Hospital Universitario Río Hortega (HURH)</b>",
  "• Bájate en <i>Paseo de Zorrilla 65 / frente Centro Comercial</i> .",
  "• Toma <b>AUVASA línea H</b> en la parada Paseo Zorrilla 71 esquina Arzobispo García Goldaráz. Si no quieres esperar 1 hora al H, tienes otras opciones disponibles (Google Maps): <a href=\"https://maps.app.goo.gl/BUiw18KJTXbMZJYP6/\">Consulta otras opciones aquí/</a>",
  "",
  "🎓 <b>Campus Miguel Delibes (UVa)</b>",
  "• Bájate en <i>Paseo de Zorrilla 65 frente Centro Comercial</i>.",
  "• Toma <b>AUVASA, línea 2 (San Pedro Regalado)</b> o <b> </b> <a href=\"https://maps.app.goo.gl/pCK8sAYJv4Jndi3p6/\">Consulta otras opciones aquí/</a> ",
  "",
  "🛒 <b>Plaza Mayor</b>",
  "• Bájate en <i>Paseo de Zorrilla 65 frente Centro Comercial</i>.",
  "• Toma la línea AUVASA que prefieras (1 o 2). <a href=\"https://maps.app.goo.gl/rtJj9kffZSbMrXpr6/\">Consulta otras opciones aquí/</a> ",
  "",
  "🏥 <b>Hospital Clínico Universitario de Valladolid (HCUV)</b>",
  "• Bájate en <i>Paseo Zorrilla 65 frente Centro Comercial</i>.",
  "• Toma <b>AUVASA línea 1/2 (la que prefieras)</b> dirección Covaresa / San Pedro Regalado. Tardarás 17 minutos (8 paradas). Bajate en "Avenida Ramón y Cajal 3 Hospital Clínico" ",
  "",
  "🚉 <b>Estación de tren</b>",
  "• Fin de línea: parada 1 (Estación de Autobuses). Sal de la Estación, y a continuación, continua por Calle Recondo 7 minutos a pie. <a href=\"https://maps.app.goo.gl/HVBZKDrtfmqtdFkA6/\">Consulta la ruta a pie aquí/</a> ",
  "",
  "🗺️ Consulta rutas AUVASA en <a href=\"https://www.auvasa.es\">auvasa.es</a> o el proyecto vecinal <a href=\"https://vallabus.com\">VallaBus</a>.",
].join("\n");
