// Contenido estático de tarifas y transbordos AUVASA.
// Fuentes: web ArroyoBus, Junta CyL (BusCyL), AUVASA.

export const TARIFAS_TEXT = [
  "🎫 <b>Tarifas y títulos de transporte</b>",
  "",
  "<b>Billete sencillo</b>",
  "• Compra a bordo. Consulta el precio actualizado en <a href=\"https://arroyobus.lovable.app\">arroyobus.lovable.app</a>.",
  "",
  "<b>Tarjeta BusCyL</b> 💳",
  "Sustituye a los antiguos carnés de transporte gratuito y abonos metropolitanos de la Junta de Castilla y León.",
  "• <b>Gratuita</b> para jóvenes (&lt;25), mayores de 65, personas con discapacidad y familias numerosas (según baremos).",
  "• Descuentos generales para el resto de usuarios.",
  "• <b>Transbordo gratuito</b> con AUVASA (Valladolid) dentro de 60 minutos.",
  "• Solicítala en <a href=\"https://buscyl.jcyl.es\">buscyl.jcyl.es</a> o en oficinas de la Junta.",
  "",
  "<b>Cómo usarla</b>",
  "1. Acerca la tarjeta al validador al subir.",
  "2. Si haces transbordo, vuelve a validar en el segundo bus (el sistema aplica la gratuidad automáticamente).",
  "",
  "ℹ️ Escribe /combinar para ver nodos de transbordo con AUVASA.",
].join("\n");

export const COMBINAR_TEXT = [
  "🔁 <b>Combinar con AUVASA (Valladolid)</b>",
  "",
  "Con la tarjeta <b>BusCyL</b> el transbordo entre ArroyoBus y AUVASA es <b>gratuito</b> (dentro de 60 min).",
  "",
  "<b>Nodos de transbordo recomendados:</b>",
  "",
  "🏥 <b>Hospital Río Hortega</b>",
  "• Bájate en <i>Paseo de Zorrilla / El Corte Inglés</i> (parada 2).",
  "• Toma <b>AUVASA L7</b> dirección Covaresa/H. Río Hortega.",
  "",
  "🎓 <b>Campus Miguel Delibes (UVa)</b>",
  "• Bájate en <i>Estación de Autobuses</i> (parada 1).",
  "• Toma <b>AUVASA L2</b> o <b>L7</b> dirección Belén/Universidad.",
  "",
  "🛒 <b>Centro de Valladolid / Plaza España</b>",
  "• Bájate en <i>Paseo de Zorrilla / El Corte Inglés</i> (parada 2).",
  "• Cualquier línea AUVASA que suba por Zorrilla (C1, C2, 2, 7…).",
  "",
  "🏥 <b>Hospital Clínico</b>",
  "• Toma <b>AUVASA línea 1/2 (la que prefieras)</b> dirección Covaresa / San Pedro Regalado. Tardarás 17 minutos (8 paradas). Bájate en \"Avenida Ramón y Cajal 3 Hospital Clínico\".",
  "",
  "🚉 <b>Estación de tren / Autobuses</b>",
  "• Fin de línea: parada 1 (Estación de Autobuses).",
  "",
  "🗺️ Consulta rutas AUVASA en <a href=\"https://www.auvasa.es\">auvasa.es</a> o el proyecto vecinal <a href=\"https://vallabus.com\">VallaBus</a>.",
].join("\n");
