// Contenido estático de tarifas y transbordos AUVASA.
// Fuentes: web ArroyoBus, Junta CyL (BusCyL), AUVASA.

export const TARIFAS_TEXT = [
  "🎫 <b>Tarifas y títulos de transporte</b>",
  "",
  "<b>Billete sencillo</b>",
  "• Compra a bordo. Coste del billete sencillo 1,80€.",
  "",
  "<b>Tarjeta BusCyL</b> 💳",
  "Sustituye a los antiguos carnés de transporte gratuito y abonos metropolitanos de la Junta de Castilla y León.",
  "• <b>Gratuita</b> para todos los empadronados en la comunidad de Castilla y León.",
  "• Descuentos generales para todos los usuarios.",
  "• Solicítala en <a href=\"https://buscyl.es\">buscyl.es</a> o en oficinas de la Junta/Estación.",
  "",
  "<b>Cómo usarla</b>",
  "1. Acerca la tarjeta al escáner-validador al subir. (cámara con flash)",
  "O si usas la tarjeta metropolitana, acércala al lector con 3 rayitas.",
  "",
  "ℹ️ Escribe /combinar para ver nodos de transbordo con AUVASA.",
].join("\n");

export const COMBINAR_TEXT = [
  "🔁 <b>Combinar con AUVASA (Valladolid)</b>",
  "",
  "Con la tarjeta <b>BusCyL</b> el transbordo entre ArroyoBus y AUVASA <b>NO es gratuito</b>. Deberás usar la \"Tarjeta de Servicios Municipales\" (bonobús), QR Auvasa o Bono Joven, Bono30... Más información en la aplicación <a href=\"https://www.auvasa.es/aviso/pasate-a-auvasa-pay/\">AUVASA PAY</a> o en <a href=\"https://www.auvasa.es/tarifas-y-medios-de-pago/\">medios de pago AUVASA</a>.",
  "",
  "<b>Nodos de transbordo recomendados:</b>",
  "",
  "🏥 <b>Hospital Universitario Río Hortega (HURH)</b>",
  "• Bájate en Paseo de Zorrilla 65 frente Centro Comercial.",
  "• Toma AUVASA líneas: 9, C1, 6, H, 7. Elige tu ruta o <a href=\"https://maps.app.goo.gl/B86bUg8aP7Bkof7E6?g_st=ic\">consulta los transbordos aquí</a>.",
  "",
  "🎓 <b>Campus Miguel Delibes (UVa)</b>",
  "• Bájate en Estación de Autobuses y ve hacia la <a href=\"https://maps.app.goo.gl/w84xyKY8YYsS6eez5?g_st=ic\">parada de AUVASA Calle Recondo 4</a>. De ahí toma AUVASA línea 2 dirección San Pedro Regalado y bájate en Plaza Carmen Ferreiro. <a href=\"https://maps.app.goo.gl/DDgR98A6taZbyPCF7?g_st=ic\">Consulta más opciones de ruta aquí</a>.",
  "",
  "🛒 <b>Plaza Mayor / Plaza España</b>",
  "• <b>Plaza Mayor:</b> Bájate en Paseo de Zorrilla 65 frente Centro Comercial y toma AUVASA línea 1/2 y bájate en Plaza Fuente Dorada. <a href=\"https://maps.app.goo.gl/dTJAJPkmS88cnBqE8?g_st=ic\">Consulta más opciones de ruta aquí</a>.",
  "• <b>Plaza España:</b> Bájate en Estación de Autobuses y continúa por Calle Recondo, Calle Gamazo y Plaza Madrid. <a href=\"https://maps.app.goo.gl/reKoN2kcb8NSNrhh6?g_st=ic\">Consulta la ruta aquí</a>.",
  "",
  "🏥 <b>Hospital Clínico Universitario de Valladolid (HCUV)</b>",
  "• Toma AUVASA línea 1/2 (la que prefieras) dirección Covaresa / San Pedro Regalado. Tardarás 17 minutos (8 paradas). Bájate en \"Avenida Ramón y Cajal 3 Hospital Clínico\". <a href=\"https://maps.app.goo.gl/mav2mYbSc2DkAATC7?g_st=ic\">Consulta la ruta aquí</a>.",
  "",
  "🚉 <b>Estación de tren Valladolid - Campo Grande</b>",
  "• Bájate en Estación de Autobuses, y dirígete hacia el este por Calle Recondo. <a href=\"https://maps.app.goo.gl/8YQFeMcPnC43562cA?g_st=ic\">Consulta la ruta aquí</a>.",
  "",
  "🗺️ Consulta rutas AUVASA en <a href=\"https://www.auvasa.es\">auvasa.es</a> o el proyecto vecinal <a href=\"https://vallabus.es\">VallaBus</a>.",
].join("\n");
