/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoliticaPrivacidadRouteImport } from './routes/politica-privacidad'
import { Route as PoliticaCookiesRouteImport } from './routes/politica-cookies'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as BusesRouteImport } from './routes/buses'
import { Route as AvisosRouteImport } from './routes/avisos'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as AsistentesRouteImport } from './routes/asistentes'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParadaSlugRouteImport } from './routes/parada/$slug'
import { Route as AvisosSanAntonioRouteImport } from './routes/avisos.san-antonio'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiStopsIndexRouteImport } from './routes/api/stops/index'
import { Route as ApiBusesIndexRouteImport } from './routes/api/buses/index'
import { Route as ApiStopsStopIdRouteImport } from './routes/api/stops/$stopId'
import { Route as ApiGtfsRtVehiclePositionsRouteImport } from './routes/api/gtfs-rt/vehicle-positions'
import { Route as ApiGtfsRtTripUpdatesRouteImport } from './routes/api/gtfs-rt/trip-updates'
import { Route as ApiBusesVehicleIdRouteImport } from './routes/api/buses/$vehicleId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp/webhook'
import { Route as ApiPublicVoiceStopRouteImport } from './routes/api/public/voice/stop'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicTelegramTickRouteImport } from './routes/api/public/telegram/tick'
import { Route as ApiPublicTelegramBroadcastRouteImport } from './routes/api/public/telegram/broadcast'
import { Route as ApiPublicAlexaSkillRouteImport } from './routes/api/public/alexa/skill'

const PoliticaPrivacidadRoute = PoliticaPrivacidadRouteImport.update({
  id: '/politica-privacidad',
  path: '/politica-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaCookiesRoute = PoliticaCookiesRouteImport.update({
  id: '/politica-cookies',
  path: '/politica-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const BusesRoute = BusesRouteImport.update({
  id: '/buses',
  path: '/buses',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisosRoute = AvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistentesRoute = AsistentesRouteImport.update({
  id: '/asistentes',
  path: '/asistentes',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParadaSlugRoute = ParadaSlugRouteImport.update({
  id: '/parada/$slug',
  path: '/parada/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisosSanAntonioRoute = AvisosSanAntonioRouteImport.update({
  id: '/san-antonio',
  path: '/san-antonio',
  getParentRoute: () => AvisosRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStopsIndexRoute = ApiStopsIndexRouteImport.update({
  id: '/api/stops/',
  path: '/api/stops/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBusesIndexRoute = ApiBusesIndexRouteImport.update({
  id: '/api/buses/',
  path: '/api/buses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStopsStopIdRoute = ApiStopsStopIdRouteImport.update({
  id: '/api/stops/$stopId',
  path: '/api/stops/$stopId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGtfsRtVehiclePositionsRoute =
  ApiGtfsRtVehiclePositionsRouteImport.update({
    id: '/api/gtfs-rt/vehicle-positions',
    path: '/api/gtfs-rt/vehicle-positions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGtfsRtTripUpdatesRoute = ApiGtfsRtTripUpdatesRouteImport.update({
  id: '/api/gtfs-rt/trip-updates',
  path: '/api/gtfs-rt/trip-updates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBusesVehicleIdRoute = ApiBusesVehicleIdRouteImport.update({
  id: '/api/buses/$vehicleId',
  path: '/api/buses/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicVoiceStopRoute = ApiPublicVoiceStopRouteImport.update({
  id: '/api/public/voice/stop',
  path: '/api/public/voice/stop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramTickRoute = ApiPublicTelegramTickRouteImport.update({
  id: '/api/public/telegram/tick',
  path: '/api/public/telegram/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramBroadcastRoute =
  ApiPublicTelegramBroadcastRouteImport.update({
    id: '/api/public/telegram/broadcast',
    path: '/api/public/telegram/broadcast',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAlexaSkillRoute = ApiPublicAlexaSkillRouteImport.update({
  id: '/api/public/alexa/skill',
  path: '/api/public/alexa/skill',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/asistentes': typeof AsistentesRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/avisos': typeof AvisosRouteWithChildren
  '/buses': typeof BusesRoute
  '/contacto': typeof ContactoRoute
  '/mcp': typeof McpRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/avisos/san-antonio': typeof AvisosSanAntonioRoute
  '/parada/$slug': typeof ParadaSlugRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/buses/$vehicleId': typeof ApiBusesVehicleIdRoute
  '/api/gtfs-rt/trip-updates': typeof ApiGtfsRtTripUpdatesRoute
  '/api/gtfs-rt/vehicle-positions': typeof ApiGtfsRtVehiclePositionsRoute
  '/api/stops/$stopId': typeof ApiStopsStopIdRoute
  '/api/buses/': typeof ApiBusesIndexRoute
  '/api/stops/': typeof ApiStopsIndexRoute
  '/api/public/alexa/skill': typeof ApiPublicAlexaSkillRoute
  '/api/public/telegram/broadcast': typeof ApiPublicTelegramBroadcastRoute
  '/api/public/telegram/tick': typeof ApiPublicTelegramTickRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/voice/stop': typeof ApiPublicVoiceStopRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/asistentes': typeof AsistentesRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/avisos': typeof AvisosRouteWithChildren
  '/buses': typeof BusesRoute
  '/contacto': typeof ContactoRoute
  '/mcp': typeof McpRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/avisos/san-antonio': typeof AvisosSanAntonioRoute
  '/parada/$slug': typeof ParadaSlugRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/buses/$vehicleId': typeof ApiBusesVehicleIdRoute
  '/api/gtfs-rt/trip-updates': typeof ApiGtfsRtTripUpdatesRoute
  '/api/gtfs-rt/vehicle-positions': typeof ApiGtfsRtVehiclePositionsRoute
  '/api/stops/$stopId': typeof ApiStopsStopIdRoute
  '/api/buses': typeof ApiBusesIndexRoute
  '/api/stops': typeof ApiStopsIndexRoute
  '/api/public/alexa/skill': typeof ApiPublicAlexaSkillRoute
  '/api/public/telegram/broadcast': typeof ApiPublicTelegramBroadcastRoute
  '/api/public/telegram/tick': typeof ApiPublicTelegramTickRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/voice/stop': typeof ApiPublicVoiceStopRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/asistentes': typeof AsistentesRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/avisos': typeof AvisosRouteWithChildren
  '/buses': typeof BusesRoute
  '/contacto': typeof ContactoRoute
  '/mcp': typeof McpRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/avisos/san-antonio': typeof AvisosSanAntonioRoute
  '/parada/$slug': typeof ParadaSlugRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/buses/$vehicleId': typeof ApiBusesVehicleIdRoute
  '/api/gtfs-rt/trip-updates': typeof ApiGtfsRtTripUpdatesRoute
  '/api/gtfs-rt/vehicle-positions': typeof ApiGtfsRtVehiclePositionsRoute
  '/api/stops/$stopId': typeof ApiStopsStopIdRoute
  '/api/buses/': typeof ApiBusesIndexRoute
  '/api/stops/': typeof ApiStopsIndexRoute
  '/api/public/alexa/skill': typeof ApiPublicAlexaSkillRoute
  '/api/public/telegram/broadcast': typeof ApiPublicTelegramBroadcastRoute
  '/api/public/telegram/tick': typeof ApiPublicTelegramTickRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/voice/stop': typeof ApiPublicVoiceStopRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/asistentes'
    | '/aviso-legal'
    | '/avisos'
    | '/buses'
    | '/contacto'
    | '/mcp'
    | '/politica-cookies'
    | '/politica-privacidad'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/avisos/san-antonio'
    | '/parada/$slug'
    | '/.mcp/invoke-tool/$tool'
    | '/api/buses/$vehicleId'
    | '/api/gtfs-rt/trip-updates'
    | '/api/gtfs-rt/vehicle-positions'
    | '/api/stops/$stopId'
    | '/api/buses/'
    | '/api/stops/'
    | '/api/public/alexa/skill'
    | '/api/public/telegram/broadcast'
    | '/api/public/telegram/tick'
    | '/api/public/telegram/webhook'
    | '/api/public/voice/stop'
    | '/api/public/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/asistentes'
    | '/aviso-legal'
    | '/avisos'
    | '/buses'
    | '/contacto'
    | '/mcp'
    | '/politica-cookies'
    | '/politica-privacidad'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/avisos/san-antonio'
    | '/parada/$slug'
    | '/.mcp/invoke-tool/$tool'
    | '/api/buses/$vehicleId'
    | '/api/gtfs-rt/trip-updates'
    | '/api/gtfs-rt/vehicle-positions'
    | '/api/stops/$stopId'
    | '/api/buses'
    | '/api/stops'
    | '/api/public/alexa/skill'
    | '/api/public/telegram/broadcast'
    | '/api/public/telegram/tick'
    | '/api/public/telegram/webhook'
    | '/api/public/voice/stop'
    | '/api/public/whatsapp/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/asistentes'
    | '/aviso-legal'
    | '/avisos'
    | '/buses'
    | '/contacto'
    | '/mcp'
    | '/politica-cookies'
    | '/politica-privacidad'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/avisos/san-antonio'
    | '/parada/$slug'
    | '/.mcp/invoke-tool/$tool'
    | '/api/buses/$vehicleId'
    | '/api/gtfs-rt/trip-updates'
    | '/api/gtfs-rt/vehicle-positions'
    | '/api/stops/$stopId'
    | '/api/buses/'
    | '/api/stops/'
    | '/api/public/alexa/skill'
    | '/api/public/telegram/broadcast'
    | '/api/public/telegram/tick'
    | '/api/public/telegram/webhook'
    | '/api/public/voice/stop'
    | '/api/public/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRoute
  AsistentesRoute: typeof AsistentesRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  AvisosRoute: typeof AvisosRouteWithChildren
  BusesRoute: typeof BusesRoute
  ContactoRoute: typeof ContactoRoute
  McpRoute: typeof McpRoute
  PoliticaCookiesRoute: typeof PoliticaCookiesRoute
  PoliticaPrivacidadRoute: typeof PoliticaPrivacidadRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ParadaSlugRoute: typeof ParadaSlugRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiBusesVehicleIdRoute: typeof ApiBusesVehicleIdRoute
  ApiGtfsRtTripUpdatesRoute: typeof ApiGtfsRtTripUpdatesRoute
  ApiGtfsRtVehiclePositionsRoute: typeof ApiGtfsRtVehiclePositionsRoute
  ApiStopsStopIdRoute: typeof ApiStopsStopIdRoute
  ApiBusesIndexRoute: typeof ApiBusesIndexRoute
  ApiStopsIndexRoute: typeof ApiStopsIndexRoute
  ApiPublicAlexaSkillRoute: typeof ApiPublicAlexaSkillRoute
  ApiPublicTelegramBroadcastRoute: typeof ApiPublicTelegramBroadcastRoute
  ApiPublicTelegramTickRoute: typeof ApiPublicTelegramTickRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  ApiPublicVoiceStopRoute: typeof ApiPublicVoiceStopRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/politica-privacidad': {
      id: '/politica-privacidad'
      path: '/politica-privacidad'
      fullPath: '/politica-privacidad'
      preLoaderRoute: typeof PoliticaPrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-cookies': {
      id: '/politica-cookies'
      path: '/politica-cookies'
      fullPath: '/politica-cookies'
      preLoaderRoute: typeof PoliticaCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buses': {
      id: '/buses'
      path: '/buses'
      fullPath: '/buses'
      preLoaderRoute: typeof BusesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avisos': {
      id: '/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AvisosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asistentes': {
      id: '/asistentes'
      path: '/asistentes'
      fullPath: '/asistentes'
      preLoaderRoute: typeof AsistentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parada/$slug': {
      id: '/parada/$slug'
      path: '/parada/$slug'
      fullPath: '/parada/$slug'
      preLoaderRoute: typeof ParadaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avisos/san-antonio': {
      id: '/avisos/san-antonio'
      path: '/san-antonio'
      fullPath: '/avisos/san-antonio'
      preLoaderRoute: typeof AvisosSanAntonioRouteImport
      parentRoute: typeof AvisosRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stops/': {
      id: '/api/stops/'
      path: '/api/stops'
      fullPath: '/api/stops/'
      preLoaderRoute: typeof ApiStopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/buses/': {
      id: '/api/buses/'
      path: '/api/buses'
      fullPath: '/api/buses/'
      preLoaderRoute: typeof ApiBusesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stops/$stopId': {
      id: '/api/stops/$stopId'
      path: '/api/stops/$stopId'
      fullPath: '/api/stops/$stopId'
      preLoaderRoute: typeof ApiStopsStopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gtfs-rt/vehicle-positions': {
      id: '/api/gtfs-rt/vehicle-positions'
      path: '/api/gtfs-rt/vehicle-positions'
      fullPath: '/api/gtfs-rt/vehicle-positions'
      preLoaderRoute: typeof ApiGtfsRtVehiclePositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gtfs-rt/trip-updates': {
      id: '/api/gtfs-rt/trip-updates'
      path: '/api/gtfs-rt/trip-updates'
      fullPath: '/api/gtfs-rt/trip-updates'
      preLoaderRoute: typeof ApiGtfsRtTripUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/buses/$vehicleId': {
      id: '/api/buses/$vehicleId'
      path: '/api/buses/$vehicleId'
      fullPath: '/api/buses/$vehicleId'
      preLoaderRoute: typeof ApiBusesVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/voice/stop': {
      id: '/api/public/voice/stop'
      path: '/api/public/voice/stop'
      fullPath: '/api/public/voice/stop'
      preLoaderRoute: typeof ApiPublicVoiceStopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/tick': {
      id: '/api/public/telegram/tick'
      path: '/api/public/telegram/tick'
      fullPath: '/api/public/telegram/tick'
      preLoaderRoute: typeof ApiPublicTelegramTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/broadcast': {
      id: '/api/public/telegram/broadcast'
      path: '/api/public/telegram/broadcast'
      fullPath: '/api/public/telegram/broadcast'
      preLoaderRoute: typeof ApiPublicTelegramBroadcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/alexa/skill': {
      id: '/api/public/alexa/skill'
      path: '/api/public/alexa/skill'
      fullPath: '/api/public/alexa/skill'
      preLoaderRoute: typeof ApiPublicAlexaSkillRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AvisosRouteChildren {
  AvisosSanAntonioRoute: typeof AvisosSanAntonioRoute
}

const AvisosRouteChildren: AvisosRouteChildren = {
  AvisosSanAntonioRoute: AvisosSanAntonioRoute,
}

const AvisosRouteWithChildren =
  AvisosRoute._addFileChildren(AvisosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRoute,
  AsistentesRoute: AsistentesRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  AvisosRoute: AvisosRouteWithChildren,
  BusesRoute: BusesRoute,
  ContactoRoute: ContactoRoute,
  McpRoute: McpRoute,
  PoliticaCookiesRoute: PoliticaCookiesRoute,
  PoliticaPrivacidadRoute: PoliticaPrivacidadRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ParadaSlugRoute: ParadaSlugRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiBusesVehicleIdRoute: ApiBusesVehicleIdRoute,
  ApiGtfsRtTripUpdatesRoute: ApiGtfsRtTripUpdatesRoute,
  ApiGtfsRtVehiclePositionsRoute: ApiGtfsRtVehiclePositionsRoute,
  ApiStopsStopIdRoute: ApiStopsStopIdRoute,
  ApiBusesIndexRoute: ApiBusesIndexRoute,
  ApiStopsIndexRoute: ApiStopsIndexRoute,
  ApiPublicAlexaSkillRoute: ApiPublicAlexaSkillRoute,
  ApiPublicTelegramBroadcastRoute: ApiPublicTelegramBroadcastRoute,
  ApiPublicTelegramTickRoute: ApiPublicTelegramTickRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  ApiPublicVoiceStopRoute: ApiPublicVoiceStopRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
