/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStopsIndexRouteImport } from './routes/api/stops/index'
import { Route as ApiStopsStopIdRouteImport } from './routes/api/stops/$stopId'
import { Route as ApiGtfsRtVehiclePositionsRouteImport } from './routes/api/gtfs-rt/vehicle-positions'
import { Route as ApiGtfsRtTripUpdatesRouteImport } from './routes/api/gtfs-rt/trip-updates'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'

const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStopsIndexRoute = ApiStopsIndexRouteImport.update({
  id: '/api/stops/',
  path: '/api/stops/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStopsStopIdRoute = ApiStopsStopIdRouteImport.update({
  id: '/api/stops/$stopId',
  path: '/api/stops/$stopId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGtfsRtVehiclePositionsRoute =
  ApiGtfsRtVehiclePositionsRouteImport.update({
    id: '/api/gtfs-rt/vehicle-positions',
    path: '/api/gtfs-rt/vehicle-positions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGtfsRtTripUpdatesRoute = ApiGtfsRtTripUpdatesRouteImport.update({
  id: '/api/gtfs-rt/trip-updates',
  path: '/api/gtfs-rt/trip-updates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/contacto': typeof ContactoRoute
  '/api/gtfs-rt/trip-updates': typeof ApiGtfsRtTripUpdatesRoute
  '/api/gtfs-rt/vehicle-positions': typeof ApiGtfsRtVehiclePositionsRoute
  '/api/stops/$stopId': typeof ApiStopsStopIdRoute
  '/api/stops/': typeof ApiStopsIndexRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/contacto': typeof ContactoRoute
  '/api/gtfs-rt/trip-updates': typeof ApiGtfsRtTripUpdatesRoute
  '/api/gtfs-rt/vehicle-positions': typeof ApiGtfsRtVehiclePositionsRoute
  '/api/stops/$stopId': typeof ApiStopsStopIdRoute
  '/api/stops': typeof ApiStopsIndexRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/contacto': typeof ContactoRoute
  '/api/gtfs-rt/trip-updates': typeof ApiGtfsRtTripUpdatesRoute
  '/api/gtfs-rt/vehicle-positions': typeof ApiGtfsRtVehiclePositionsRoute
  '/api/stops/$stopId': typeof ApiStopsStopIdRoute
  '/api/stops/': typeof ApiStopsIndexRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/aviso-legal'
    | '/contacto'
    | '/api/gtfs-rt/trip-updates'
    | '/api/gtfs-rt/vehicle-positions'
    | '/api/stops/$stopId'
    | '/api/stops/'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/aviso-legal'
    | '/contacto'
    | '/api/gtfs-rt/trip-updates'
    | '/api/gtfs-rt/vehicle-positions'
    | '/api/stops/$stopId'
    | '/api/stops'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/aviso-legal'
    | '/contacto'
    | '/api/gtfs-rt/trip-updates'
    | '/api/gtfs-rt/vehicle-positions'
    | '/api/stops/$stopId'
    | '/api/stops/'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  ContactoRoute: typeof ContactoRoute
  ApiGtfsRtTripUpdatesRoute: typeof ApiGtfsRtTripUpdatesRoute
  ApiGtfsRtVehiclePositionsRoute: typeof ApiGtfsRtVehiclePositionsRoute
  ApiStopsStopIdRoute: typeof ApiStopsStopIdRoute
  ApiStopsIndexRoute: typeof ApiStopsIndexRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stops/': {
      id: '/api/stops/'
      path: '/api/stops'
      fullPath: '/api/stops/'
      preLoaderRoute: typeof ApiStopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stops/$stopId': {
      id: '/api/stops/$stopId'
      path: '/api/stops/$stopId'
      fullPath: '/api/stops/$stopId'
      preLoaderRoute: typeof ApiStopsStopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gtfs-rt/vehicle-positions': {
      id: '/api/gtfs-rt/vehicle-positions'
      path: '/api/gtfs-rt/vehicle-positions'
      fullPath: '/api/gtfs-rt/vehicle-positions'
      preLoaderRoute: typeof ApiGtfsRtVehiclePositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gtfs-rt/trip-updates': {
      id: '/api/gtfs-rt/trip-updates'
      path: '/api/gtfs-rt/trip-updates'
      fullPath: '/api/gtfs-rt/trip-updates'
      preLoaderRoute: typeof ApiGtfsRtTripUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  ContactoRoute: ContactoRoute,
  ApiGtfsRtTripUpdatesRoute: ApiGtfsRtTripUpdatesRoute,
  ApiGtfsRtVehiclePositionsRoute: ApiGtfsRtVehiclePositionsRoute,
  ApiStopsStopIdRoute: ApiStopsStopIdRoute,
  ApiStopsIndexRoute: ApiStopsIndexRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
