/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGtfsRtVehiclePositionsRouteImport } from './routes/api/gtfs-rt/vehicle-positions'
import { Route as ApiGtfsRtTripUpdatesRouteImport } from './routes/api/gtfs-rt/trip-updates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGtfsRtVehiclePositionsRoute =
  ApiGtfsRtVehiclePositionsRouteImport.update({
    id: '/api/gtfs-rt/vehicle-positions',
    path: '/api/gtfs-rt/vehicle-positions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGtfsRtTripUpdatesRoute = ApiGtfsRtTripUpdatesRouteImport.update({
  id: '/api/gtfs-rt/trip-updates',
  path: '/api/gtfs-rt/trip-updates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/gtfs-rt/trip-updates': typeof ApiGtfsRtTripUpdatesRoute
  '/api/gtfs-rt/vehicle-positions': typeof ApiGtfsRtVehiclePositionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/gtfs-rt/trip-updates': typeof ApiGtfsRtTripUpdatesRoute
  '/api/gtfs-rt/vehicle-positions': typeof ApiGtfsRtVehiclePositionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/gtfs-rt/trip-updates': typeof ApiGtfsRtTripUpdatesRoute
  '/api/gtfs-rt/vehicle-positions': typeof ApiGtfsRtVehiclePositionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/gtfs-rt/trip-updates'
    | '/api/gtfs-rt/vehicle-positions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/gtfs-rt/trip-updates' | '/api/gtfs-rt/vehicle-positions'
  id:
    | '__root__'
    | '/'
    | '/api/gtfs-rt/trip-updates'
    | '/api/gtfs-rt/vehicle-positions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGtfsRtTripUpdatesRoute: typeof ApiGtfsRtTripUpdatesRoute
  ApiGtfsRtVehiclePositionsRoute: typeof ApiGtfsRtVehiclePositionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gtfs-rt/vehicle-positions': {
      id: '/api/gtfs-rt/vehicle-positions'
      path: '/api/gtfs-rt/vehicle-positions'
      fullPath: '/api/gtfs-rt/vehicle-positions'
      preLoaderRoute: typeof ApiGtfsRtVehiclePositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gtfs-rt/trip-updates': {
      id: '/api/gtfs-rt/trip-updates'
      path: '/api/gtfs-rt/trip-updates'
      fullPath: '/api/gtfs-rt/trip-updates'
      preLoaderRoute: typeof ApiGtfsRtTripUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGtfsRtTripUpdatesRoute: ApiGtfsRtTripUpdatesRoute,
  ApiGtfsRtVehiclePositionsRoute: ApiGtfsRtVehiclePositionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
